version: "3.9"

volumes:
  goapidesignvolume:
    name: go-api-design-volume

networks:
  goapidesignnetwork:
    name: go-api-design-network

services:
  pg:
    image: postgres:13.2
    restart: on-failure
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT1}:${POSTGRES_PORT2}"
    volumes:
      - goapidesignvolume:/var/lib/postgresql/data
      - ./db/scripts:/docker-entrypoint-initdb.d/
    networks:
      - goapidesignnetwork
  goapidesign_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - pg
    volumes:
      - ./:/app
    ports:
      - 7777:7777
    networks:
      - goapidesignnetwork
    env_file:
      - .env
    entrypoint: ["/bin/bash", "./scripts/entrypoint.dev.sh"]
