FROM golang:1.16

# Working Directory
WORKDIR /app

# Expecting to get API_PORT as arguments
ARG API_PORT

# Fetch dependencies on a seperate layer as they are less likely to change on every build
# Will be cached for speeding up each build
COPY ./go.mod ./go.sum ./
RUN go mod download

# Copy source from the host to the working directory inside the container
COPY . .

# This container exposes API_PORT from .env to the outside world
EXPOSE ${API_PORT}
